import pandas as pd
import matplotlib.pyplot as plt
import os
from datetime import datetime
import numpy as np

OUTPUT_DIR = "outputs"
CHARTS_DIR = os.path.join(OUTPUT_DIR, "charts")


def setup_style():
    """Set up a clean, professional style for the charts."""
    # Use a built-in style if available, or fall back to default
    try:
        plt.style.use("seaborn-v0_8-darkgrid")
    except:
        plt.style.use("ggplot")

    plt.rcParams["font.family"] = "sans-serif"
    plt.rcParams["font.sans-serif"] = [
        "Arial",
        "DejaVu Sans",
        "Liberation Sans",
        "Bitstream Vera Sans",
        "sans-serif",
    ]
    plt.rcParams["figure.figsize"] = (10, 6)
    plt.rcParams["axes.titlesize"] = 14
    plt.rcParams["axes.labelsize"] = 12


def ensure_dirs():
    os.makedirs(CHARTS_DIR, exist_ok=True)


def plot_pie_chart(df, label_col, value_col, title, filename):
    """Generic function to plot a pie chart."""
    if df.empty:
        return

    plt.figure(figsize=(10, 7))

    # Sort by value
    df = df.sort_values(by=value_col, ascending=False)

    # Group small slices into "Other" if too many
    if len(df) > 10:
        top_10 = df.head(10)
        other_val = df.iloc[10:][value_col].sum()
        other_row = pd.DataFrame({label_col: ["Other"], value_col: [other_val]})
        df = pd.concat([top_10, other_row])

    # Colors
    colors = plt.cm.Paired(np.linspace(0, 1, len(df)))

    wedges, texts, autotexts = plt.pie(
        df[value_col],
        labels=df[label_col],
        autopct="%1.1f%%",
        startangle=90,
        colors=colors,
        pctdistance=0.85,
        explode=[0.05] + [0] * (len(df) - 1),  # Explode the first slice
    )

    # Draw a circle at the center of pie to make it look like a donut
    centre_circle = plt.Circle((0, 0), 0.70, fc="white")
    fig = plt.gcf()
    fig.gca().add_artist(centre_circle)

    plt.title(title, pad=20)
    plt.axis("equal")
    plt.tight_layout()
    plt.savefig(os.path.join(CHARTS_DIR, filename), dpi=300)
    plt.close()


def plot_bar_chart(df, label_col, value_col, title, filename, color="#3498db"):
    """Generic function to plot a horizontal bar chart."""
    if df.empty:
        return

    plt.figure(figsize=(12, 8))

    # Sort for bar chart (top items at top)
    df = df.sort_values(by=value_col, ascending=True).tail(15)  # Top 15

    bars = plt.barh(df[label_col], df[value_col], color=color)

    # Add value labels
    for bar in bars:
        width = bar.get_width()
        plt.text(
            width,
            bar.get_y() + bar.get_height() / 2,
            f" €{width:,.0f}",
            ha="left",
            va="center",
            fontsize=10,
        )

    plt.title(title)
    plt.xlabel("Exposure (€)")
    plt.tight_layout()
    plt.savefig(os.path.join(CHARTS_DIR, filename), dpi=300)
    plt.close()


def generate_dashboard(total_value, top_10_df):
    """Generates the Markdown dashboard."""

    md = [
        "# 📊 Portfolio Summary Dashboard",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d')}",
        f"**Total Portfolio Value:** €{total_value:,.2f}",
        "",
        "## 🌍 Asset Allocation & Exposure",
        "| Asset Class | Sector | Geography |",
        "|:---:|:---:|:---:|",
        "| ![Asset Class](charts/asset_class.png) | ![Sector](charts/sector.png) | ![Geography](charts/geography.png) |",
        "",
        "## 🏆 Top 15 Holdings",
        "![Top Holdings](charts/top_holdings.png)",
        "",
        "### Top 10 Details",
        "| Name | ISIN | Sector | Value (€) | % |",
        "|---|---|---|---:|---:|",
    ]

    for _, row in top_10_df.iterrows():
        name = row.get("name", "Unknown")
        isin = row.get("isin", "N/A")
        sector = row.get("sector", "Unknown")
        val = row.get("total_exposure", 0)
        pct = row.get("portfolio_percentage", 0)
        md.append(f"| {name} | `{isin}` | {sector} | €{val:,.2f} | {pct:.2f}% |")

    md.append("")
    md.append("---")
    md.append("*Generated by True Exposure Pipeline*")

    with open(os.path.join(OUTPUT_DIR, "PORTFOLIO_SUMMARY.md"), "w") as f:
        f.write("\n".join(md))


def run_visualization():
    print("--- Generating Visualizations ---")
    setup_style()
    ensure_dirs()

    # Load Data
    try:
        report_path = os.path.join(OUTPUT_DIR, "enriched_exposure_report.csv")
        df = pd.read_csv(report_path)

        if df.empty:
            print("No data to visualize.")
            return

        total_value = df["total_exposure"].sum()

        # 1. Asset Class (if available)
        if "asset_class" in df.columns:
            ac_df = df.groupby("asset_class")["total_exposure"].sum().reset_index()
            plot_pie_chart(
                ac_df,
                "asset_class",
                "total_exposure",
                "Asset Allocation",
                "asset_class.png",
            )

        # 2. Sector
        if "sector" in df.columns:
            sec_df = df.groupby("sector")["total_exposure"].sum().reset_index()
            plot_pie_chart(
                sec_df, "sector", "total_exposure", "Sector Exposure", "sector.png"
            )

        # 3. Geography
        if "geography" in df.columns:
            geo_df = df.groupby("geography")["total_exposure"].sum().reset_index()
            plot_pie_chart(
                geo_df,
                "geography",
                "total_exposure",
                "Geographic Exposure",
                "geography.png",
            )

        # 4. Top Holdings
        top_10 = df.nlargest(15, "total_exposure")
        plot_bar_chart(
            top_10, "name", "total_exposure", "Top 15 Holdings", "top_holdings.png"
        )

        # Generate Dashboard
        generate_dashboard(total_value, top_10.head(10))
        print(f"Dashboard saved to {os.path.join(OUTPUT_DIR, 'PORTFOLIO_SUMMARY.md')}")

    except Exception as e:
        print(f"Visualization failed: {e}")


if __name__ == "__main__":
    run_visualization()
